upstream smart_souq_backend {
    server localhost:4001;
    server localhost:4002;
    server localhost:4003;
}
server {
    listen 80;
    location /api {
        proxy_pass http://smart_souq_backend;
    }
}
