import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  FaAmazon, 
  FaEbay, 
  FaShopify, 
  FaStore, 
  FaPercentage, 
  FaShareAlt, 
  FaChartBar,
  FaShoppingCart,
  FaDollarSign,
  FaTag,
  FaFire,
  FaStar,
  FaShoppingBag,
  FaBoxOpen,
  FaLaptop,
  FaMobileAlt,
  FaHeadphones,
  FaGamepad,
  FaHome,
  FaTshirt
} from 'react-icons/fa';

const EcommercePlatform = () => {
  const [activeTab, setActiveTab] = useState('all');
  // تحديث: استخدام useState لحساب الأرباح بدلاً من getElementById لضمان توافق Vercel
  const [calculatedEarnings, setCalculatedEarnings] = useState("0.00");

  const products = [
    {
      id: 1,
      name: 'Apple iPhone 15 Pro Max',
      price: 1099,
      originalPrice: 1199,
      discount: '8%',
      commission: '4.5%',
      store: 'Amazon',
      storeIcon: <FaAmazon />,
      rating: 4.8,
      image: <FaMobileAlt />,
      category: 'electronics',
      affiliateLink: '#',
      sales: 1245,
    },
    {
      id: 2,
      name: 'Samsung Galaxy S24 Ultra',
      price: 899,
      originalPrice: 999,
      discount: '10%',
      commission: '5%',
      store: 'Ebay',
      storeIcon: <FaEbay />,
      rating: 4.7,
      image: <FaMobileAlt />,
      category: 'electronics',
      affiliateLink: '#',
      sales: 987,
    },
    {
      id: 3,
      name: 'Sony WH-1000XM5 Headphones',
      price: 349,
      originalPrice: 399,
      discount: '12%',
      commission: '6%',
      store: 'Shopify',
      storeIcon: <FaShopify />,
      rating: 4.9,
      image: <FaHeadphones />,
      category: 'electronics',
      affiliateLink: '#',
      sales: 2156,
    },
    {
      id: 4,
      name: 'MacBook Pro 16" M3 Max',
      price: 2499,
      originalPrice: 2799,
      discount: '11%',
      commission: '3.5%',
      store: 'Amazon',
      storeIcon: <FaAmazon />,
      rating: 4.9,
      image: <FaLaptop />,
      category: 'electronics',
      affiliateLink: '#',
      sales: 743,
    },
    {
      id: 5,
      name: 'Dyson V15 Detect Vacuum',
      price: 699,
      originalPrice: 799,
      discount: '12%',
      commission: '7%',
      store: 'Noon',
      storeIcon: <FaStore />,
      rating: 4.6,
      image: <FaHome />,
      category: 'home',
      affiliateLink: '#',
      sales: 1123,
    },
    {
      id: 6,
      name: 'Nintendo Switch OLED',
      price: 349,
      originalPrice: 399,
      discount: '12%',
      commission: '6.5%',
      store: 'Ebay',
      storeIcon: <FaEbay />,
      rating: 4.8,
      image: <FaGamepad />,
      category: 'gaming',
      affiliateLink: '#',
      sales: 1854,
    },
    {
      id: 7,
      name: 'Nike Air Max 270',
      price: 149,
      originalPrice: 179,
      discount: '17%',
      commission: '8%',
      store: 'Amazon',
      storeIcon: <FaAmazon />,
      rating: 4.5,
      image: <FaTshirt />,
      category: 'fashion',
      affiliateLink: '#',
      sales: 3256,
    },
    {
      id: 8,
      name: 'PlayStation 5 Digital Edition',
      price: 449,
      originalPrice: 499,
      discount: '10%',
      commission: '5.5%',
      store: 'Shopify',
      storeIcon: <FaShopify />,
      rating: 4.8,
      image: <FaGamepad />,
      category: 'gaming',
      affiliateLink: '#',
      sales: 1643,
    },
  ];

  const stores = [
    { id: 'amazon', name: 'Amazon', icon: <FaAmazon />, commission: '3-10%', products: 1200 },
    { id: 'ebay', name: 'Ebay', icon: <FaEbay />, commission: '2-8%', products: 850 },
    { id: 'shopify', name: 'Shopify', icon: <FaShopify />, commission: '4-12%', products: 650 },
    { id: 'noon', name: 'Noon', icon: <FaStore />, commission: '5-15%', products: 750 },
  ];

  const categories = [
    { id: 'all', name: 'الكل', icon: <FaShoppingBag />, count: 1250 },
    { id: 'electronics', name: 'إلكترونيات', icon: <FaMobileAlt />, count: 450 },
    { id: 'home', name: 'أدوات منزلية', icon: <FaHome />, count: 280 },
    { id: 'gaming', name: 'ألعاب', icon: <FaGamepad />, count: 320 },
    { id: 'f